// magicRegistry is auto-generated by Nexus from each component's
// observedAttributes. Never edit registry.ts manually.
import { magicRegistry } from './registry.ts';

const sanitizeText = (text: string): string => {
  const risky = /<(script|img|iframe|object|embed|svg|on\w+)[^>]*?>/gi;
  return risky.test(text)
    ? text.replace(/</g, '&lt;').replace(/>/g, '&gt;')
    : text;
};

const hashData = async (data: string): Promise<string> => {
  const encoder = new TextEncoder();
  const buffer = await crypto.subtle.digest("SHA-256", encoder.encode(data));
  return [...new Uint8Array(buffer)].map(b => b.toString(16).padStart(2, "0")).join("");
};

customElements.define('magic-error', class extends HTMLElement {
  static get observedAttributes() {
    return ['data-message', 'data-hint'];
  }

  attributeChangedCallback() { this._render(); }
  connectedCallback() { this._render(); }

  private _render() {
    const message = this.getAttribute('data-message') ?? '';
    const hint    = this.getAttribute('data-hint')    ?? '';
    if (!message && !hint) return;

    const escape = (str: string) => str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');

    this.innerHTML = `
      ⚠️ <strong>${escape(message)}</strong><br/>
      <small>${escape(hint)}</small>
    `;
  }
});

let _magicIdCounter = 0;

const getMagicId = (el: Element): string => {
  if (!el.hasAttribute('data-magic-id')) {
    el.setAttribute('data-magic-id', String(++_magicIdCounter));
  }
  return el.getAttribute('data-magic-id')!;
};

const renderMagicError = (el: Element, missingAttr: string, hint: string) => {
  const magicId = getMagicId(el);
  if (document.querySelector(`magic-error[data-for="${magicId}"]`)) return;

  const tagName = el.tagName.toLowerCase();

  const error = document.createElement('magic-error');
  error.setAttribute('data-message', `Missing "${missingAttr}" in <${tagName}>`);  // ← solo el tag
  error.setAttribute('data-hint', hint);
  error.setAttribute('data-for', magicId);

  el.classList.add('magic-error-target');
  el.appendChild(error);
};

const clearMagicError = (el: Element) => {
  const magicId = getMagicId(el);
  document.querySelector(`magic-error[data-for="${magicId}"]`)?.remove();
  el.classList.remove('magic-error-target');
};

const validateMagicComponent = (el: Element, requiredAttrs: string[], context: string) => {
  const missing = requiredAttrs.find(attr => !el.getAttribute(attr));
  if (missing) {
    const tagName = el.tagName.toLowerCase();
    renderMagicError(el, missing, `Add a ${missing}="..." attribute to your ${tagName}.`);
  } else {
    clearMagicError(el);
  }
};

const observeMagicComponents = (tagName: string, requiredAttrs: string[]) => {
  customElements.whenDefined(tagName).then(() => {
    const elements = document.querySelectorAll(tagName);
    elements.forEach(el => {
      let isValidating = false;
      
      const validate = () => {
        if (isValidating) return;
        isValidating = true;
        validateMagicComponent(el, requiredAttrs, tagName);
        isValidating = false;
      };

      const observer = new MutationObserver(() => setTimeout(validate, 0));
      observer.observe(el, { attributes: true, childList: false }); 
      setTimeout(validate, 50);
    });
  });
};

Object.entries(magicRegistry).forEach(([tag, attrs]) => {
  observeMagicComponents(tag, attrs);
});