// ============================================================
// MAGIC REGISTRY — Auto-generated by Nexus.
// Do not edit manually. Regenerated on every dev start and build.
// ============================================================

export const magicRegistry: Record<string, string[]> = {
  "magic-card": [
    "image",
    "title"
  ]
}
