// ============================================================
// MAGIC — Nexus
// Main framework orchestrator.
//
// Dev:  serves from arche/ in memory, never touches calvaria/
//       backend runs from server/ directly with Bun
//
// Prod: compiles and minifies everything into calvaria/
//       calvaria/frontend/ → browser-ready JS + static assets
//       calvaria/backend/  → server.js bundle + transpiled src/
// ============================================================

import fs, { watch } from 'fs';
import path from 'path';

// ── Constants ────────────────────────────────────────────────
const IS_PROD      = Bun.argv.includes('--prod');
const OUT_DIR      = 'calvaria';
const FRONTEND_DIR = `${OUT_DIR}/frontend`;
const BACKEND_DIR  = `${OUT_DIR}/backend`;
const SRC_DIR      = 'arche';
const SERVER_DIR   = 'server';
const PORT         = 3000;

const MIME_TYPES: Record<string, string> = {
  '.js'   : 'application/javascript',
  '.ts'   : 'application/javascript',
  '.css'  : 'text/css',
  '.html' : 'text/html',
  '.png'  : 'image/png',
  '.jpg'  : 'image/jpeg',
  '.jpeg' : 'image/jpeg',
  '.svg'  : 'image/svg+xml',
  '.ico'  : 'image/x-icon',
};

const SYSTEM_ROUTES = new Set([
  '/favicon.ico',
  '/apple-touch-icon.png',
  '/apple-touch-icon-precomposed.png',
  '/robots.txt',
  '/sitemap.xml',
]);

// ── Registry generator ───────────────────────────────────────
// Reads each component's munus.ts and extracts the array returned
// by observedAttributes. That way the registry always matches
// what the component actually declares — no manual sync needed.
//
// It writes arche/core/registry.ts which LIBRIS.ts imports.
// The file is auto-generated; never edit it by hand.

const OBSERVED_ATTRS_REGEX =
  /static\s+get\s+observedAttributes\s*\(\s*\)\s*\{[^}]*?return\s*(\[[^\]]*\])/s;

const extractObservedAttributes = (source: string): string[] => {
  const match = source.match(OBSERVED_ATTRS_REGEX);
  if (!match) return [];

  return match[1]
    .replace(/[\[\]\s]/g, '')
    .split(',')
    .map(s => s.replace(/['"]/g, '').trim())
    .filter(Boolean);
};

const generateRegistry = (): void => {
  const componentsPath = `./${SRC_DIR}/components`;
  const registryPath   = `./${SRC_DIR}/core/registry.ts`;

  const componentDirs = fs.readdirSync(componentsPath) as string[];
  const registry: Record<string, string[]> = {};

  for (const name of componentDirs) {
    const munusPath = path.join(componentsPath, name, 'munus.ts');

    if (!fs.existsSync(munusPath)) {
      console.warn(`⚠  No munus.ts found for component "${name}" — skipping.`);
      registry[name] = [];
      continue;
    }

    const source = fs.readFileSync(munusPath, 'utf-8');
    const attrs  = extractObservedAttributes(source);
    registry[name] = attrs;

    console.log(`   ✓ ${name}  →  [${attrs.join(', ') || 'no observed attributes'}]`);
  }

  const fileContent = [
    '// ============================================================',
    '// MAGIC REGISTRY — Auto-generated by Nexus.',
    '// Do not edit manually. Regenerated on every dev start and build.',
    '// ============================================================',
    '',
    `export const magicRegistry: Record<string, string[]> = ${JSON.stringify(registry, null, 2)}`,
    '',
  ].join('\n');

  fs.writeFileSync(registryPath, fileContent, 'utf-8');
  console.log(`📋 Registry written → ${registryPath} (${componentDirs.length} component/s)\n`);
};

// ── Build error formatting ───────────────────────────────────
// Bun returns BuildMessage objects with position, message and level.
// Instead of printing the raw object, we format them so that
// anyone using Magic can understand what went wrong.

type BuildMessage = {
  message: string;
  level?: string;
  position?: {
    file?   : string;
    line?   : number;
    column? : number;
  };
};

const formatBuildError = (log: BuildMessage): string => {
  const file = log.position?.file   ?? 'unknown file';
  const line = log.position?.line   ?? '?';
  const col  = log.position?.column ?? '?';

  return [
    '',
    '  ✦ Magic found a TypeScript error',
    `  ┌ File   : ${file}`,
    `  ├ Line   : ${line}, Column: ${col}`,
    `  └ Error  : ${log.message}`,
    '',
  ].join('\n');
};

// ── Filesystem helpers ───────────────────────────────────────
const copyFolder = (src: string, dest: string): void => {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });

  for (const item of fs.readdirSync(src)) {
    const srcPath  = path.join(src, item);
    const destPath = path.join(dest, item);

    fs.statSync(srcPath).isDirectory()
      ? copyFolder(srcPath, destPath)
      : fs.copyFileSync(srcPath, destPath);
  }
};

const copyStaticAssets = (): void => {
  fs.copyFileSync(`./${SRC_DIR}/index.html`, `${FRONTEND_DIR}/index.html`);
  copyFolder(`./${SRC_DIR}/styles`, `${FRONTEND_DIR}/styles`);
  copyFolder(`./${SRC_DIR}/images`, `${FRONTEND_DIR}/images`);
};

const cleanOutput = (): void => {
  if (fs.existsSync(OUT_DIR)) fs.rmSync(OUT_DIR, { recursive: true });
  fs.mkdirSync(OUT_DIR,      { recursive: true });
  fs.mkdirSync(FRONTEND_DIR, { recursive: true });
};

// ── Frontend build ───────────────────────────────────────────
// Compiles and minifies all TypeScript from arche/ for the browser.
// Output goes to calvaria/frontend/.

const buildFrontend = async (): Promise<boolean> => {
  const componentDirs    = fs.readdirSync(`./${SRC_DIR}/components`) as string[];
  const componentEntries = componentDirs.map(name =>
    `${SRC_DIR}/components/${name}/munus.ts`
  );

  const entrypoints = [
    `${SRC_DIR}/core/LIBRIS.ts`,
    `${SRC_DIR}/core/ROUTER.ts`,
    ...componentEntries,
  ];

  console.log('📦 Building frontend...');

  const result = await Bun.build({
    entrypoints,
    outdir : FRONTEND_DIR,
    root   : SRC_DIR,
    target : 'browser',
    minify : true,
  });

  if (!result.success) {
    console.error('\n❌ Frontend build failed:\n');
    result.logs.forEach(log => console.error(formatBuildError(log as BuildMessage)));
    return false;
  }

  copyStaticAssets();
  console.log(`✓ Frontend → ${FRONTEND_DIR}/\n`);
  return true;
};

// ── Backend build ────────────────────────────────────────────
// Looks for a server/ folder at the project root with an index.ts.
// If it does not exist, this step is skipped silently.
//
// Produces two outputs inside calvaria/backend/:
//   server.js  — single minified bundle, ready to run with Bun
//   src/        — transpiled files preserving folder structure (for debug)

const hasBackend = (): boolean => {
  const entry = path.join(SERVER_DIR, 'index.ts');
  return fs.existsSync(SERVER_DIR) && fs.existsSync(entry);
};

const transpileFolder = async (src: string, dest: string): Promise<boolean> => {
  if (!fs.existsSync(src)) return true;
  fs.mkdirSync(dest, { recursive: true });

  const entries = fs.readdirSync(src);

  for (const item of entries) {
    const srcPath  = path.join(src, item);
    const destPath = path.join(dest, item);

    if (fs.statSync(srcPath).isDirectory()) {
      const ok = await transpileFolder(srcPath, destPath);
      if (!ok) return false;
      continue;
    }

    if (item.endsWith('.ts')) {
      // Each .ts file is transpiled individually to preserve structure
      const result = await Bun.build({
        entrypoints : [srcPath],
        outdir      : dest,
        target      : 'bun',
        minify      : false,  // debug-friendly
      });

      if (!result.success) {
        console.error(`\n❌ Backend transpile failed on ${srcPath}:\n`);
        result.logs.forEach(log => console.error(formatBuildError(log as BuildMessage)));
        return false;
      }
    } else {
      // Non-TS files (json, env templates, etc.) are copied as-is
      fs.copyFileSync(srcPath, destPath);
    }
  }

  return true;
};

const buildBackend = async (): Promise<boolean> => {
  if (!hasBackend()) {
    console.log('ℹ  No server/ folder found — skipping backend build.\n');
    return true;
  }

  fs.mkdirSync(BACKEND_DIR, { recursive: true });

  const entry      = path.join(SERVER_DIR, 'index.ts');
  const bundleDest = path.join(BACKEND_DIR, 'server.js');
  const srcDest    = path.join(BACKEND_DIR, 'src');

  console.log('📦 Building backend...');

  // 1. Single minified bundle — what actually runs in production
  const bundleResult = await Bun.build({
    entrypoints : [entry],
    outdir      : BACKEND_DIR,
    naming      : 'server.js',
    target      : 'bun',
    minify      : true,
  });

  if (!bundleResult.success) {
    console.error('\n❌ Backend bundle failed:\n');
    bundleResult.logs.forEach(log => console.error(formatBuildError(log as BuildMessage)));
    return false;
  }

  console.log(`   ✓ Bundle  → ${bundleDest}`);

  // 2. Transpiled structure — keeps folder layout for debugging
  const transpileOk = await transpileFolder(SERVER_DIR, srcDest);
  if (!transpileOk) return false;

  console.log(`   ✓ Source  → ${srcDest}/`);
  console.log(`✓ Backend  → ${BACKEND_DIR}/\n`);
  return true;
};

// ── Dev server ───────────────────────────────────────────────
// Serves directly from arche/ without writing anything to disk.
// .ts files are transpiled on-the-fly with Bun.Transpiler.
// calvaria/ does NOT exist in dev — this is intentional.
//
// The backend is NOT managed here — run it separately with:
//   bun run server/index.ts

const startDevServer = (): void => {
  const transpiler = new Bun.Transpiler({ loader: 'ts' });

  Bun.serve({
    port : PORT,
    async fetch(req) {
      const url      = new URL(req.url);
      const pathname = url.pathname;

      // System routes — return empty to keep the console clean
      if (SYSTEM_ROUTES.has(pathname) || pathname.startsWith('/.well-known')) {
        return new Response(null, { status: 204 });
      }

      // Files with extension → look up in arche/
      if (pathname.includes('.')) {
        const ext     = path.extname(pathname);
        const rawPath = path.join(SRC_DIR, pathname);

        // Only .js requests are candidates for TS transpilation.
        // CSS, images, fonts and everything else go straight to static.
        if (ext === '.js') {
          const tsPath = path.join(SRC_DIR, pathname.replace(/\.js$/, '.ts'));
          const tsFile = Bun.file(tsPath);

          if (await tsFile.exists()) {
            const source = await tsFile.text();
            let javascript = transpiler.transformSync(source);

            // Bun.Transpiler does not rewrite import paths.
            // The browser can't resolve .ts imports, so we rewrite them to .js
            // so the dev server can intercept and transpile them on demand.
            javascript = javascript.replace(
              /from\s+['"](\.\.?\/[^'"]+)\.ts['"]/g,
              (_, p) => `from '${p}.js'`
            );

            return new Response(javascript, {
              headers: { 'Content-Type': 'application/javascript' },
            });
          }
        }

        // Static asset (css, images, fonts, html, etc.)
        const rawFile = Bun.file(rawPath);
        if (await rawFile.exists()) {
          const contentType = MIME_TYPES[ext] ?? 'application/octet-stream';
          return new Response(rawFile, {
            headers: { 'Content-Type': contentType },
          });
        }

        return new Response('Not Found', { status: 404 });
      }

      // Routes without extension → SPA fallback to index.html
      return new Response(Bun.file(`./${SRC_DIR}/index.html`));
    },
  });

  console.log(`🧙 Magic DEV running at http://localhost:${PORT}`);
  console.log(`   Frontend → arche/   (calvaria/ does not exist in dev)`);

  if (hasBackend()) {
    console.log(`   Backend  → run separately: bun run ${SERVER_DIR}/index.ts`);
  }

  console.log('');
};

// ── Production server ────────────────────────────────────────
// Serves the compiled frontend from calvaria/frontend/.
// The backend bundle (calvaria/backend/server.js) is run separately.

const startProdServer = (): void => {
  Bun.serve({
    port : PORT,
    async fetch(req) {
      const url      = new URL(req.url);
      let   pathname = url.pathname;

      if (SYSTEM_ROUTES.has(pathname) || pathname.startsWith('/.well-known')) {
        return new Response(null, { status: 204 });
      }

      if (pathname.endsWith('/')) pathname += 'index.html';

      const filePath = path.join(FRONTEND_DIR, pathname);
      const file     = Bun.file(filePath);

      if (await file.exists()) {
        const ext         = path.extname(pathname);
        const contentType = MIME_TYPES[ext] ?? 'application/octet-stream';
        return new Response(file, {
          headers: { 'Content-Type': contentType },
        });
      }

      // SPA fallback
      return new Response(Bun.file(`${FRONTEND_DIR}/index.html`));
    },
  });

  console.log(`🧙 Magic PROD running at http://localhost:${PORT}`);
  console.log(`   Frontend → ${FRONTEND_DIR}/`);

  if (hasBackend()) {
    console.log(`   Backend  → run separately: bun run ${BACKEND_DIR}/server.js`);
  }

  console.log('');
};

// ── Watcher (dev only) ───────────────────────────────────────
// In dev there is no build to re-run — the transpiler is on-the-fly.
// The watcher notifies the developer which file changed.
// If a server/ file changes, it reminds to restart the backend.

const startWatcher = (): void => {
  watch(`./${SRC_DIR}`, { recursive: true }, (_eventType, filename) => {
    if (!filename) return;

    if (
      filename.endsWith('.ts')   ||
      filename.endsWith('.html') ||
      filename.endsWith('.css')
    ) {
      console.log(`🔁 Frontend change: ${filename} — reload your browser.`);
    }
  });

  if (hasBackend()) {
    watch(`./${SERVER_DIR}`, { recursive: true }, (_eventType, filename) => {
      if (!filename) return;
      if (filename.endsWith('.ts')) {
        console.log(`🔁 Backend change: ${filename} — restart your backend process.`);
      }
    });
  }

  console.log('👁  Watcher active on arche/' + (hasBackend() ? ` and ${SERVER_DIR}/` : ''));
};

// ── Main orchestrator ────────────────────────────────────────

// Always regenerate the registry first so LIBRIS.ts is never stale,
// regardless of whether we are in dev or prod mode.
generateRegistry();

if (IS_PROD) {
  // Production: clean, build frontend + backend, serve frontend
  cleanOutput();

  const frontendOk = await buildFrontend();
  if (!frontendOk) process.exit(1);

  const backendOk = await buildBackend();
  if (!backendOk) process.exit(1);

  console.log(`✨ Magic build complete → ${OUT_DIR}/`);
  console.log(`   ${FRONTEND_DIR}/`);
  if (hasBackend()) console.log(`   ${BACKEND_DIR}/`);
  console.log('');

  startProdServer();
} else {
  // Dev: serve frontend in memory, backend runs independently
  startDevServer();
  startWatcher();
}
